name: Build .deb Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Theos
      - name: Set up Theos
        run: |
          # Cài đặt các công cụ cần thiết
          sudo apt update
          sudo apt install -y git wget curl unzip perl clang make dpkg
          
          # Cloning Theos repository
          git clone https://github.com/theos/theos.git $HOME/theos
          
          # Tải và cài đặt dm.pl
          wget -O $HOME/theos/bin/dm.pl https://raw.githubusercontent.com/theos/theos/master/bin/dm.pl
          chmod +x $HOME/theos/bin/dm.pl
          
          # Tải SDK từ GitHub
          wget -O $HOME/theos/sdks/main.zip https://github.com/theos/sdks/archive/refs/heads/main.zip
          unzip -q $HOME/theos/sdks/main.zip -d $HOME/theos/sdks
          
          # Di chuyển SDK và dọn dẹp
          mv $HOME/theos/sdks/sdks-main/iPhoneOS14.5.sdk $HOME/theos/sdks/
          rm -rf $HOME/theos/sdks/sdks-main
          rm $HOME/theos/sdks/main.zip
          
          # Thiết lập môi trường Theos
          echo "export THEOS=$HOME/theos" >> $GITHUB_ENV

      # Build the package
      - name: Build .deb package
        run: |
          export THEOS=$HOME/theos
          make package

      # Upload .deb file as artifact
      - name: Upload .deb file
        uses: actions/upload-artifact@v3
        with:
          name: YouTube-X
          path: ./packages/*.deb
