name: Build .deb Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Theos
      - name: Set up Theos
        run: |
          sudo apt update
          sudo apt install -y git wget curl unzip perl clang make dpkg
          git clone https://github.com/theos/theos.git $HOME/theos
          wget -O $HOME/theos/bin/dm.pl https://raw.githubusercontent.com/theos/theos/master/bin/dm.pl
          chmod +x $HOME/theos/bin/dm.pl
          echo "export THEOS=$HOME/theos" >> $GITHUB_ENV

      # Download iOS SDK
      - name: Download iOS SDK
        run: |
          wget https://github.com/xybp888/iOS-SDKs/releases/download/iOS14.0-iOS16.4SDKs/iPhoneOS14.0-iOS16.4SDKs.zip -O /tmp/ios-sdk.zip
          unzip /tmp/ios-sdk.zip -d /tmp
          # Kiểm tra xem SDK đã được giải nén đúng chưa và di chuyển SDK vào đúng thư mục
          ls /tmp/iOS14.0-iOS16.4SDKs
          mv /tmp/iOS14.0-iOS16.4SDKs/iPhoneOS16.4.sdk /home/runner/ios-sdk

      # Build the package
      - name: Build .deb
        run: |
          export THEOS=$HOME/theos
          export SDK_PATH=/home/runner/ios-sdk/iPhoneOS16.4.sdk
          echo "SDK_PATH=$SDK_PATH" >> $GITHUB_ENV
          make package

      # Upload artifact (the .deb file)
      - name: Upload .deb file
        uses: actions/upload-artifact@v3
        with:
          name: YouTube-X
          path: ./packages/*.deb
