name: Build .deb Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Theos
      - name: Set up Theos
        run: |
          sudo apt update
          sudo apt install -y git wget curl unzip perl clang make dpkg
          git clone https://github.com/theos/theos.git $HOME/theos
          wget -O $HOME/theos/bin/dm.pl https://raw.githubusercontent.com/theos/theos/master/bin/dm.pl
          chmod +x $HOME/theos/bin/dm.pl
          wget -O $HOME/theos/sdks/iPhoneOS14.5.sdk.zip https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.zip
          unzip -q $HOME/theos/sdks/iPhoneOS14.5.sdk.zip -d $HOME/theos/sdks
          rm $HOME/theos/sdks/iPhoneOS14.5.sdk.zip
          echo "export THEOS=$HOME/theos" >> $GITHUB_ENV

      # Build the package
      - name: Build .deb
        run: |
          export THEOS=$HOME/theos
          make package

      # Upload artifact (the .deb file)
      - name: Upload .deb file
        uses: actions/upload-artifact@v3
        with:
          name: YouTube-X
          path: ./packages/*.deb
