name: Build .deb Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Theos
      - name: Set up Theos
        run: |
          sudo apt update
          sudo apt install -y git wget curl unzip perl clang make dpkg
          git clone https://github.com/theos/theos.git $HOME/theos
          wget -O $HOME/theos/bin/dm.pl https://raw.githubusercontent.com/theos/theos/master/bin/dm.pl
          chmod +x $HOME/theos/bin/dm.pl
          echo "export THEOS=$HOME/theos" >> $GITHUB_ENV

      # Download iOS SDK
      - name: Download iOS SDK
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.5.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      # Build the package
      - name: Build .deb
        run: |
          export THEOS=$HOME/theos
          export SDK_PATH=$THEOS/sdks/iPhoneOS16.5.sdk
          echo "SDK_PATH=$SDK_PATH" >> $GITHUB_ENV
          make package

      # Upload artifact (the .deb file)
      - name: Upload .deb file
        uses: actions/upload-artifact@v3
        with:
          name: YouTube-X
          path: ./packages/*.deb
